### ISSUE TITLE
HTML content on Logout warning isn't sanitized

### ISSUE THREAD

**Issue by lndanh-axonivy** [axonivy-market/portal#726]
Hi there,

I am using Axon Ivy Portal and got this issue. When Im working in a task, and click to Logout, a confirmation dialog was display with unsanitized text. Please review it.

Thank you

Product: Axon Ivy Designer
Version: 11.2.1.2401191301
Build: 2024-01-19

![image](https://github.com/axonivy-market/portal/assets/127722015/cecf1d0c-f7e9-4445-b49b-d7645abab6c2)

**Comment by ntloc-axonivy** [comment]
Hi @lndanh-axonivy, this is a known bug that has already been fixed in version 11.3. Please update to the latest version.

**Comment by lndanh-axonivy** [comment]
Hi @ntloc-axonivy 
Thank you for your quickly response
